using System.Collections.Generic;
using System.Collections;
using UnityEngine;
using System;
public class AudioManager : MonoBehaviour
{
    public static AudioManager instance;
    public Sound[] sounds;
    // Start is called before the first frame update
    void Start()
    {
        if(instance !=null)
        {
            Destroy(gameObject);
        }
        else
        {
            instance = this;
            DontDestroyOnLoad(gameObject);  //一定要写吗？
        }
        //添加所有的AudioSource组件
        foreach(Sound s in sounds)
        {
            s.source = gameObject.AddComponent<AudioSource>();
            s.source.clip = s.clip;
            s.source.volume = s.volume;
            s.source.pitch = s.pitch;
            s.source.loop = s.loop ;   
        }
    }
    public void Play(string name)
    {
        Sound s = Array.Find(sounds, s => s.name == name);
        s.source.Play();
    }
    public void Stop(string name)
    {
        Sound s = Array.Find(sounds, s => s.name == name);
        s.source.Stop();
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
